In [1]:
import pandas as pd
from pathlib import Path

In [2]:
file_path = Path('..', 'Dataset', 'pre-processed', 'final_breaker_data', 'final_preprocessed_410_data.csv')

In [3]:
file_path.exists()

True

In [4]:
df = pd.read_csv(file_path)

In [5]:
df.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Unnamed: 6,Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),...,CH5 Open-Velocity (m/s),CH5 Test Run,DCRM Res CH6 in uOhm,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,phase,CH1 Resistance Break,CH2 Resistance Break
0,0.000,0.000,0.000,0.044,0.0,0.0,,0,0,0,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN
1,0.000,0.000,0.000,0.029,0.0,0.0,,0,0,0,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN
2,0.000,0.022,0.000,0.029,0.0,0.0,,0,0,0,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN
3,0.044,0.066,0.022,0.044,0.0,0.0,,0,0,0,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN
4,0.059,0.088,0.044,0.044,0.0,0.0,,0,0,0,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN

In [6]:
df.drop(columns=['Unnamed: 6'], inplace=True)

In [7]:
df.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH5 Open-Velocity (m/s),CH5 Test Run,DCRM Res CH6 in uOhm,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,phase,CH1 Resistance Break,CH2 Resistance Break
0,0.000,0.000,0.000,0.044,0.0,0.0,0,0,0,0.44,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN
1,0.000,0.000,0.000,0.029,0.0,0.0,0,0,0,-0.04,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN
2,0.000,0.022,0.000,0.029,0.0,0.0,0,0,0,0.12,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN
3,0.044,0.066,0.022,0.044,0.0,0.0,0,0,0,-0.04,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN
4,0.059,0.088,0.044,0.044,0.0,0.0,0,0,0,-0.04,...,0,TR2,0,0,0,0,TR2,B,NaN,NaN

In [8]:
df['breaker_id'] = '410'

In [9]:
df['breaker_id']

0        410
1        410
2        410
3        410
4        410
        ...
13495    410
13496    410
13497    410
13498    410
13499    410
Name: breaker_id, Length: 13500, dtype: str

In [10]:
df.to_csv(file_path, index=False)