In [1]:
import pandas as pd
from pathlib import Path

In [ ]:
file_path = Path('..', 'Dataset', 'pre-processed', 'final_breaker_data', 'final_preprocessed_407_data.csv')

In [3]:
file_path.exists()

True

In [4]:
df = pd.read_csv(file_path)

In [5]:
df.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Unnamed: 6,Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),...,DCRM Res CH6 in uOhm,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,phase,CH3 Resistance Break,CH4 Resistance Break,CH3 Bounce Break,CH4 Bounce Break
0,0.000,0.000,0.000,0.029,0.0,0.0,,0,0,0,...,457.14,0,0,0,TR2,Y,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,0.037,0.0,0.0,,0,0,0,...,555.80,0,0,0,TR2,Y,NaN,NaN,NaN,NaN
2,0.000,0.000,0.000,0.051,0.0,0.0,,0,0,0,...,555.80,0,0,0,TR2,Y,NaN,NaN,NaN,NaN
3,0.029,0.044,0.037,0.029,0.0,0.0,,0,0,0,...,555.80,0,0,0,TR2,Y,NaN,NaN,NaN,NaN
4,0.066,0.073,0.066,0.051,0.0,0.0,,0,0,0,...,555.80,0,0,0,TR2,Y,NaN,NaN,NaN,NaN

In [7]:
df.drop(columns=['Unnamed: 6'], inplace=True)

In [8]:
df.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,DCRM Res CH6 in uOhm,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,phase,CH3 Resistance Break,CH4 Resistance Break,CH3 Bounce Break,CH4 Bounce Break
0,0.000,0.000,0.000,0.029,0.0,0.0,0,0,0,0.85,...,457.14,0,0,0,TR2,Y,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,0.037,0.0,0.0,0,0,0,-0.26,...,555.80,0,0,0,TR2,Y,NaN,NaN,NaN,NaN
2,0.000,0.000,0.000,0.051,0.0,0.0,0,0,0,-0.02,...,555.80,0,0,0,TR2,Y,NaN,NaN,NaN,NaN
3,0.029,0.044,0.037,0.029,0.0,0.0,0,0,0,0.14,...,555.80,0,0,0,TR2,Y,NaN,NaN,NaN,NaN
4,0.066,0.073,0.066,0.051,0.0,0.0,0,0,0,-0.02,...,555.80,0,0,0,TR2,Y,NaN,NaN,NaN,NaN

In [9]:
df['breaker_id'] = '407'

In [10]:
df['breaker_id']

0        407
1        407
2        407
3        407
4        407
        ...
13495    407
13496    407
13497    407
13498    407
13499    407
Name: breaker_id, Length: 13500, dtype: str

In [11]:
df.to_csv(file_path, index=False)