In [12]:
import pandas as pd
from pathlib import Path
import numpy as np

In [21]:
data_path = Path('..', 'Dataset', 'processed_402_R_faulty.csv')
data_path.exists()

True

In [22]:
df = pd.read_csv(data_path)

In [23]:
df.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH6 Open-Velocity (m/s),CH6 Test Run,phase,CH3 Bounce Break,CH4 Bounce Break,breaker_id,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.drop(columns=[col for col in df.columns if col.startswith('Unnamed')], inplace=True)

In [17]:
df.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,DCRM Current CH5 in Amp,CH5 Close-Velocity (m/s),CH5 Open-Velocity (m/s),CH5 Test Run,DCRM Res CH6 in uOhm,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,phase
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0,0,0.12,TR4,368.25,0,0,0.12,TR4,R
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0,0,0.12,TR4,379.98,0,0,0.12,TR4,R
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0,0,0.12,TR4,378.02,0,0,0.12,TR4,R
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0,0,0.12,TR4,393.65,0,0,0.12,TR4,R
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0,0,0.12,TR4,393.65,0,0,0.12,TR4,R

In [18]:
req_cols =  ['Coil Current C1 (A)', 'Coil Current C2 (A)', 'Coil Current C3 (A)',
       'Coil Current C4 (A)', 'Coil Current C5 (A)', 'Coil Current C6 (A)',
       'Contact Travel T1 (mm)', 'Contact Travel T2 (mm)',
       'Contact Travel T3 (mm)', 'Contact Travel T4 (mm)',
       'Contact Travel T5 (mm)', 'Contact Travel T6 (mm)',
       'DCRM Res CH1 in uOhm', 'DCRM Current CH1 in Amp',
       'CH1 Close-Velocity (m/s)', 'CH1 Open-Velocity (m/s)', 'CH1 Test Run',
       'DCRM Res CH2 in uOhm', 'DCRM Current CH2 in Amp',
       'CH2 Close-Velocity (m/s)', 'CH2 Open-Velocity (m/s)', 'CH2 Test Run',
       'DCRM Res CH3 in uOhm', 'DCRM Current CH3 in Amp',
       'CH3 Close-Velocity (m/s)', 'CH3 Open-Velocity (m/s)', 'CH3 Test Run',
       'DCRM Res CH4 in uOhm', 'DCRM Current CH4 in Amp',
       'CH4 Close-Velocity (m/s)', 'CH4 Open-Velocity (m/s)', 'CH4 Test Run',
       'DCRM Res CH5 in uOhm', 'DCRM Current CH5 in Amp',
       'CH5 Close-Velocity (m/s)', 'CH5 Open-Velocity (m/s)', 'CH5 Test Run',
       'DCRM Res CH6 in uOhm', 'DCRM Current CH6 in Amp',
       'CH6 Close-Velocity (m/s)', 'CH6 Open-Velocity (m/s)', 'CH6 Test Run',
       'phase', 'CH3 Resistance Break', 'CH4 Resistance Break',
       'CH3 Bounce Break', 'CH4 Bounce Break', 'breaker_id',
       'CH1 Resistance Break', 'CH2 Resistance Break', 'CH1 Bounce Break',
       'CH2 Bounce Break']

add_cols = []
    
for col in req_cols:
    if col in df.columns:
        continue
    else:
        add_cols.append(col)

for col in add_cols:
    df[col] = np.nan
        
print(list(set((df.columns)) - set(req_cols)))

[]

In [19]:
df.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH6 Open-Velocity (m/s),CH6 Test Run,phase,CH3 Bounce Break,CH4 Bounce Break,breaker_id,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0.12,TR4,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.to_csv(data_path, index=False)

In [26]:
cols_df = ['Coil Current C1 (A)', 'Coil Current C2 (A)', 'Coil Current C3 (A)',
       'Coil Current C4 (A)', 'Coil Current C5 (A)', 'Coil Current C6 (A)',
       'Contact Travel T1 (mm)', 'Contact Travel T2 (mm)',
       'Contact Travel T3 (mm)', 'Contact Travel T4 (mm)',
       'Contact Travel T5 (mm)', 'Contact Travel T6 (mm)',
       'DCRM Res CH1 in uOhm', 'DCRM Current CH1 in Amp',
       'CH1 Close-Velocity (m/s)', 'CH1 Open-Velocity (m/s)', 'CH1 Test Run',
       'DCRM Res CH2 in uOhm', 'DCRM Current CH2 in Amp',
       'CH2 Close-Velocity (m/s)', 'CH2 Open-Velocity (m/s)', 'CH2 Test Run',
       'DCRM Res CH3 in uOhm', 'DCRM Current CH3 in Amp',
       'CH3 Close-Velocity (m/s)', 'CH3 Open-Velocity (m/s)', 'CH3 Test Run',
       'CH3 Resistance Break', 'DCRM Res CH4 in uOhm',
       'DCRM Current CH4 in Amp', 'CH4 Close-Velocity (m/s)',
       'CH4 Open-Velocity (m/s)', 'CH4 Test Run', 'CH4 Resistance Break',
       'DCRM Res CH5 in uOhm', 'DCRM Current CH5 in Amp',
       'CH5 Close-Velocity (m/s)', 'CH5 Open-Velocity (m/s)', 'CH5 Test Run',
       'DCRM Res CH6 in uOhm', 'DCRM Current CH6 in Amp',
       'CH6 Close-Velocity (m/s)', 'CH6 Open-Velocity (m/s)', 'CH6 Test Run',
       'CH3 Bounce Break', 'CH4 Bounce Break', 'CH1 Resistance Break',
       'CH2 Resistance Break', 'CH1 Bounce Break', 'CH2 Bounce Break']


cols = ['Coil Current C1 (A)', 'Coil Current C2 (A)', 'Coil Current C3 (A)',
       'Coil Current C4 (A)', 'Coil Current C5 (A)', 'Coil Current C6 (A)',
       'Contact Travel T1 (mm)', 'Contact Travel T2 (mm)',
       'Contact Travel T3 (mm)', 'Contact Travel T4 (mm)',
       'Contact Travel T5 (mm)', 'Contact Travel T6 (mm)',
       'DCRM Res CH1 in uOhm', 'DCRM Current CH1 in Amp',
       'CH1 Close-Velocity (m/s)', 'CH1 Open-Velocity (m/s)', 'CH1 Test Run',
       'DCRM Res CH2 in uOhm', 'DCRM Current CH2 in Amp',
       'CH2 Close-Velocity (m/s)', 'CH2 Open-Velocity (m/s)', 'CH2 Test Run',
       'DCRM Res CH3 in uOhm', 'DCRM Current CH3 in Amp',
       'CH3 Close-Velocity (m/s)', 'CH3 Open-Velocity (m/s)', 'CH3 Test Run',
       'DCRM Res CH4 in uOhm', 'DCRM Current CH4 in Amp',
       'CH4 Close-Velocity (m/s)', 'CH4 Open-Velocity (m/s)', 'CH4 Test Run',
       'DCRM Res CH5 in uOhm', 'DCRM Current CH5 in Amp',
       'CH5 Close-Velocity (m/s)', 'CH5 Open-Velocity (m/s)', 'CH5 Test Run',
       'DCRM Res CH6 in uOhm', 'DCRM Current CH6 in Amp',
       'CH6 Close-Velocity (m/s)', 'CH6 Open-Velocity (m/s)', 'CH6 Test Run',
       'CH3 Resistance Break', 'CH4 Resistance Break',
       'CH3 Bounce Break', 'CH4 Bounce Break',
       'CH1 Resistance Break', 'CH2 Resistance Break', 'CH1 Bounce Break',
       'CH2 Bounce Break']
i = 0
for col in cols and cols_df:
    print(col)
    i+=1
print(i)

Coil Current C1 (A)
Coil Current C2 (A)
Coil Current C3 (A)
Coil Current C4 (A)
Coil Current C5 (A)
Coil Current C6 (A)
Contact Travel T1 (mm)
Contact Travel T2 (mm)
Contact Travel T3 (mm)
Contact Travel T4 (mm)
Contact Travel T5 (mm)
Contact Travel T6 (mm)
DCRM Res CH1 in uOhm
DCRM Current CH1 in Amp
CH1 Close-Velocity (m/s)
CH1 Open-Velocity (m/s)
CH1 Test Run
DCRM Res CH2 in uOhm
DCRM Current CH2 in Amp
CH2 Close-Velocity (m/s)
CH2 Open-Velocity (m/s)
CH2 Test Run
DCRM Res CH3 in uOhm
DCRM Current CH3 in Amp
CH3 Close-Velocity (m/s)
CH3 Open-Velocity (m/s)
CH3 Test Run
CH3 Resistance Break
DCRM Res CH4 in uOhm
DCRM Current CH4 in Amp
CH4 Close-Velocity (m/s)
CH4 Open-Velocity (m/s)
CH4 Test Run
CH4 Resistance Break
DCRM Res CH5 in uOhm
DCRM Current CH5 in Amp
CH5 Close-Velocity (m/s)
CH5 Open-Velocity (m/s)
CH5 Test Run
DCRM Res CH6 in uOhm
DCRM Current CH6 in Amp
CH6 Close-Velocity (m/s)
CH6 Open-Velocity (m/s)
CH6 Test Run
CH3 Bounce Break
CH4 Bounce Break
CH1 Resistance Break
CH2 Resistance Break
CH1 Bounce Break
CH2 Bounce Break
50

In [ ]:
.exists(),.exists()

(True, True)

In [36]:
ad = pd.read_csv(Path('..','Dataset', 'pre-processed', 'final_preprocessed_good_data.csv'))

da = pd.read_csv(Path('..','Dataset', 'processed_good_data.csv'))

/tmp/ipykernel_162022/640019378.py:1: DtypeWarning: Columns (0: CH3 Resistance Break, 1: CH4 Resistance Break, 2: CH3 Bounce Break, 3: CH4 Bounce Break, 4: CH1 Resistance Break, 5: CH2 Resistance Break, 6: CH1 Bounce Break, 7: CH2 Bounce Break) have mixed types. Specify dtype option on import or set low_memory=False.
  ad = pd.read_csv(Path('..','Dataset', 'pre-processed', 'final_preprocessed_good_data.csv'))
/tmp/ipykernel_162022/640019378.py:3: DtypeWarning: Columns (0: CH3 Resistance Break, 1: CH4 Resistance Break, 2: CH1 Bounce Break, 3: CH2 Bounce Break) have mixed types. Specify dtype option on import or set low_memory=False.
  da = pd.read_csv(Path('..','Dataset', 'processed_good_data.csv'))

In [37]:
ad.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Resistance Break,CH4 Resistance Break,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break
0,0.000,0.000,0.000,0.029,0.0,0.0,0.0,0.0,0.0,0.85,...,0,TR2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,0.037,0.0,0.0,0.0,0.0,0.0,-0.26,...,0,TR2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.000,0.000,0.000,0.051,0.0,0.0,0.0,0.0,0.0,-0.02,...,0,TR2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.029,0.044,0.037,0.029,0.0,0.0,0.0,0.0,0.0,0.14,...,0,TR2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.066,0.073,0.066,0.051,0.0,0.0,0.0,0.0,0.0,-0.02,...,0,TR2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
da.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Unnamed: 6,Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),...,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,phase,status,CH1 Bounce Break,CH2 Bounce Break,CH1 Resistance Break,CH2 Resistance Break
0,0.015,0.029,0.015,0.029,0.0,0.0,,0,0,0,...,0,0,0.12,TR4,R,faulty,NaN,NaN,NaN,NaN
1,0.007,0.022,0.000,0.037,0.0,0.0,,0,0,0,...,0,0,0.12,TR4,R,faulty,NaN,NaN,NaN,NaN
2,0.051,0.007,0.000,0.066,0.0,0.0,,0,0,0,...,0,0,0.12,TR4,R,faulty,NaN,NaN,NaN,NaN
3,0.161,0.029,0.000,0.051,0.0,0.0,,0,0,0,...,0,0,0.12,TR4,R,faulty,NaN,NaN,NaN,NaN
4,0.286,0.022,0.015,0.029,0.0,0.0,,0,0,0,...,0,0,0.12,TR4,R,faulty,NaN,NaN,NaN,NaN

In [40]:
ad['phase'] = da['phase']

In [41]:
ad['phase']

0          R
1          R
2          R
3          R
4          R
        ...
49495    NaN
49496    NaN
49497    NaN
49498    NaN
49499    NaN
Name: phase, Length: 49500, dtype: str

In [42]:
da['phase']

0              R
1              R
2              R
3              R
4              R
          ...
17995    Unknown
17996    Unknown
17997    Unknown
17998    Unknown
17999    Unknown
Name: phase, Length: 18000, dtype: str

In [43]:
import joblib

In [44]:
model = joblib.load(Path('..', 'models', 'isolation_forest_final_final.pkl'))

In [47]:
scores = model.decision_function(df_scaled)

NameError: name 'df_scaled' is not defined